---
- name: 安装mysql实例
  hosts: all
  gather_facts: no
  vars:
    - MYSQL_USER: mysql
    - MYSQL_MULTI_DIR: "/home/mysql/multi"
    - MYSQL_PORT: "{{mysql_port}}"
    - MYSQL_BASE_DIR: "{{MYSQL_MULTI_DIR}}/{{MYSQL_PORT}}/private"
    - MYSQL_VERSION: "{{mysql_version}}"
    - MYSQL_FILE_NAME: "{{MYSQL_VERSION}}.tar.gz"
    - MYSQL_CONF_NAME: "my.cnf"
    - MYSQL_SERVER_SCRIPT: "mysql.server"
    - SOURCE_MYSQL_DIR: "/Users/gaochao/gaochao-git/gaochao_repo/devpos/django_backend/apps/ansible_task/playbook/mysql/roles/install_mysql/files"
    - TEMPLATES_DIR: "/Users/gaochao/gaochao-git/gaochao_repo/devpos/django_backend/apps/ansible_task/playbook/mysql/roles/install_mysql/templates"
    - COPY_MYSQL_FILE_TO_DIR: "/tmp"
  tasks:
  - name: 判断端口目录是否存在
    stat: path={{MYSQL_MULTI_DIR}}/{{MYSQL_PORT}}
    register: mysql_port_dir_stat
#  - name: print
#    debug:
#      var: mysql_port_dir_stat
  - name: 如果端口目录已经存在则退出执行
    fail:
      msg: "{{MYSQL_PORT}}端口目录存在,退出后续操作"
    when: mysql_port_dir_stat.stat.exists == True
  - name: 判断端口是否运行中
    wait_for:
      port: "{{MYSQL_PORT}}"
      timeout: 1
      state: started
    register: mysqld_service_status
    ignore_errors: yes
#  - name: print
#    debug:
#      var: mysqld_service_status
  - name: 如果端口已经运行则退出执行
    fail:
      msg: "{{MYSQL_PORT}}端口运行中,退出后续操作"
    when: mysqld_service_status.failed == False
  - name: 创建实例目录
    file: name={{ item }} state=directory owner={{ MYSQL_USER }} group={{ MYSQL_USER }} mode=0755 recurse=yes
    with_items:
      - "{{MYSQL_MULTI_DIR}}/{{MYSQL_PORT}}/binlog"
      - "{{MYSQL_MULTI_DIR}}/{{MYSQL_PORT}}/data"
      - "{{MYSQL_MULTI_DIR}}/{{MYSQL_PORT}}/etc"
      - "{{MYSQL_MULTI_DIR}}/{{MYSQL_PORT}}/lock"
      - "{{MYSQL_MULTI_DIR}}/{{MYSQL_PORT}}/log"
      - "{{MYSQL_MULTI_DIR}}/{{MYSQL_PORT}}/pid"
      - "{{MYSQL_MULTI_DIR}}/{{MYSQL_PORT}}/socket"
      - "{{MYSQL_MULTI_DIR}}/{{MYSQL_PORT}}/tmp"
  - name: 拷贝mysql安装包到所有主机
    copy: src={{SOURCE_MYSQL_DIR}}/{{MYSQL_FILE_NAME}} dest={{COPY_MYSQL_FILE_TO_DIR}} owner=root group=root
  - name: 拷贝my.cnf到所有主机
    copy: src={{TEMPLATES_DIR}}/{{MYSQL_CONF_NAME}} dest={{MYSQL_MULTI_DIR}}/{{MYSQL_PORT}}/etc owner=root group=root
  - name: 判断mysql.server启动脚本是否存在
    stat: path=/etc/init.d/mysql.server
    register: mysql_server_script_stat
  - name: 拷贝mysql.server到所有主机
    copy: src={{TEMPLATES_DIR}}/{{MYSQL_SERVER_SCRIPT}} dest=/etc/init.d owner=root group=root mode=0755
    when: mysql_server_script_stat.stat.exists == False
  - name: 替换端口
    replace:
      dest: "{{MYSQL_MULTI_DIR}}/{{MYSQL_PORT}}/etc/my.cnf"
      regexp: "(3306)"
      replace: "{{MYSQL_PORT}}"
  - name: 将中控机器压缩包解压到目标服务器
    unarchive: src={{COPY_MYSQL_FILE_TO_DIR}}/{{MYSQL_FILE_NAME}} dest={{COPY_MYSQL_FILE_TO_DIR}} owner=root group=root copy=no
  - name: 将解压后的包拷贝到base目录
    command: mv {{COPY_MYSQL_FILE_TO_DIR}}/{{MYSQL_VERSION}} {{MYSQL_BASE_DIR}}
  - name: mysql初始化
    shell: "{{ MYSQL_BASE_DIR }}/bin/mysqld --defaults-file={{MYSQL_MULTI_DIR}}/{{MYSQL_PORT}}/etc/my.cnf --initialize-insecure"
  - name: 启动mysqld
    shell: /etc/init.d/mysql.server -P {{MYSQL_PORT}} start
  - name: 等待mysqld启动
    wait_for:
      port: "{{MYSQL_PORT}}"
      timeout: 10
      state: started